INSERT INTO COUNTRY_MASTER VALUES(1,'India');
INSERT INTO COUNTRY_MASTER VALUES(2,'USA');

INSERT INTO STATE_MASTER VALUES(1,1,'AndhraPradesh');
INSERT INTO STATE_MASTER VALUES(2,1,'Karnataka');
INSERT INTO STATE_MASTER VALUES(3,2,'NewJersey');
INSERT INTO STATE_MASTER VALUES(4,2,'Ohio');

INSERT INTO CITY_MASTER VALUES(1,'Vizeg',1);
INSERT INTO CITY_MASTER VALUES(2,'Gunter',1);
INSERT INTO CITY_MASTER VALUES(3,'Banglore',2);
INSERT INTO CITY_MASTER VALUES(4,'Mysore',2);
INSERT INTO CITY_MASTER VALUES(5,'Westwood',3);
INSERT INTO CITY_MASTER VALUES(6,'Maywwod',3);
INSERT INTO CITY_MASTER VALUES(7,'Oakwood',4);
INSERT INTO CITY_MASTER VALUES(8,'Cuyhoga',4);
